# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i25EPj8J1Nrv7SkIcNO9RX1Da90YsWn9
"""

# data_cleaning.ipynb

import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# Cargar el dataset
data = pd.read_csv('data/datos_estudiantes.csv')

# Mostrar un resumen inicial del dataset
print(data.info())
print(data.describe())

# Ver si hay valores nulos
print("Valores nulos en el dataset:")
print(data.isnull().sum())

# Si no hay valores nulos, continuamos con la normalización
# Normalización de las columnas numéricas
scaler = MinMaxScaler()

# Variables que normalizaremos
columns_to_scale = ['Edad', 'Promedio_calificaciones_semestre_anterior',
                    'Asignaturas_reprobadas', 'Asignaturas_aprobadas',
                    'Numero_semestres_matriculado', 'Asistencia',
                    'Distancia_universidad']

data[columns_to_scale] = scaler.fit_transform(data[columns_to_scale])

# Verificamos el dataset limpio
print("Dataset después de la normalización:")
print(data.head())

# Guardar el dataset limpio
data.to_csv('data/cleaned_dataset.csv', index=False)